https://aitoolsdirectory.com/

https://artificialanalysis.ai/

In [1]:
import nltk

In [ ]:
!pip install nltk

In [2]:
corpus = '''Hello welcome,to Gen AI NLP Lecture
Please do activity ! to become expert in NLP'''

from nltk.tokenize import sent_tokenize
sent_tokenize(corpus)

LookupError: 
**********************************************************************
  Resource punkt_tab not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('punkt_tab')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load tokenizers/punkt_tab/english/

  Searched in:
    - 'C:\\Users\\karth/nltk_data'
    - 'C:\\ProgramData\\anaconda3\\nltk_data'
    - 'C:\\ProgramData\\anaconda3\\share\\nltk_data'
    - 'C:\\ProgramData\\anaconda3\\lib\\nltk_data'
    - 'C:\\Users\\karth\\AppData\\Roaming\\nltk_data'
    - 'C:\\nltk_data'
    - 'D:\\nltk_data'
    - 'E:\\nltk_data'
**********************************************************************


In [3]:
import nltk
nltk.download('punkt_tab')

corpus = '''Hello welcome,to Gen AI NLP Lecture
Please do activity ! to become expert in NLP'''

from nltk.tokenize import sent_tokenize
sent_tokenize(corpus)

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\karth\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt_tab.zip.


['Hello welcome,to Gen AI NLP Lecture\nPlease do activity !',
 'to become expert in NLP']

In [4]:
# Tokenization 
# paragrapgh ->sentence 
# paragraph ->words

from nltk.tokenize import word_tokenize

In [6]:
word_tokenize(corpus)

['Hello',
 'welcome',
 ',',
 'to',
 'Gen',
 'AI',
 'NLP',
 'Lecture',
 'Please',
 'do',
 'activity',
 '!',
 'to',
 'become',
 'expert',
 'in',
 'NLP']

In [11]:
msg="Hello arun,How are you doing ? OK. I am doing NLP activities's code ab'c data1.data2"
sent_tokenize(msg)

['Hello arun,How are you doing ?',
 'OK.',
 "I am doing NLP activities's code ab'c data1.data2"]

In [12]:

documents = sent_tokenize(msg)
print(type(documents))

<class 'list'>


In [9]:
for var in documents:
    print(var)

Hello arun,How are you doing ?
OK.
I am doing NLP activity


In [14]:
from nltk.tokenize import wordpunct_tokenize
wordpunct_tokenize(msg)

['Hello',
 'arun',
 ',',
 'How',
 'are',
 'you',
 'doing',
 '?',
 'OK',
 '.',
 'I',
 'am',
 'doing',
 'NLP',
 'activities',
 "'",
 's',
 'code',
 'ab',
 "'",
 'c',
 'data1',
 '.',
 'data2']

In [16]:
word_tokenize(msg)

['Hello',
 'arun',
 ',',
 'How',
 'are',
 'you',
 'doing',
 '?',
 'OK',
 '.',
 'I',
 'am',
 'doing',
 'NLP',
 'activities',
 "'s",
 'code',
 'ab',
 "'",
 'c',
 'data1.data2']

In [17]:
from nltk.tokenize import TreebankWordTokenizer
tokenizer_obj = TreebankWordTokenizer()
tokenizer_obj.tokenize(msg)

['Hello',
 'arun',
 ',',
 'How',
 'are',
 'you',
 'doing',
 '?',
 'OK.',
 'I',
 'am',
 'doing',
 'NLP',
 'activities',
 "'s",
 'code',
 "ab'c",
 'data1.data2']

In [18]:
from nltk.stem import PorterStemmer
obj_stemming = PorterStemmer()

obj_stemming.stem('eating') # reduce root word - stemming

'eat'

In [19]:
obj_stemming.stem('history')

'histori'

In [20]:
obj_stemming.stem('congratulations')

'congratul'

In [23]:
# Regular Expression 
# ---------------------
# input ->Regx patterns
from nltk.stem import RegexpStemmer
# obj = RegexpStemmer('RegPattern',min=<Count>)
reg_stemmer = RegexpStemmer('ing$|s$|e$')
reg_stemmer.stem('eating')

'eat'

In [25]:
reg_stemmer.stem('abcd')

'abcd'

In [26]:
reg_stemmer.stem('abcde')

'abcd'

In [27]:
reg_stemmer.stem('concepts')

'concept'

In [ ]:
# Activity1
#-------------
1. import nltk module 
2. using PorterStemmer - omit given root words 

Given_list => ["words","eats","eatern","writing","writes","programming","program","history","finally"
               "finalized"]


In [29]:
Given_list = ["words","eats","eatern","writing","writes","programming","program","history","finally",
               "finalized"]

stemming_obj = PorterStemmer()
for var in Given_list:
    print(var+"-->"+stemming_obj.stem(var))

words-->word
eats-->eat
eatern-->eatern
writing-->write
writes-->write
programming-->program
program-->program
history-->histori
finally-->final
finalized-->final


In [30]:
Given_list = ["words","eats","eatern","writing","writes","programming","program","history","finally",
               "finalized"]

reg_obj = RegexpStemmer('ing$|s$|e$|able$')
for var in Given_list:
    print(var+"-->"+reg_obj.stem(var))

words-->word
eats-->eat
eatern-->eatern
writing-->writ
writes-->write
programming-->programm
program-->program
history-->history
finally-->finally
finalized-->finalized


In [31]:
from nltk.stem import SnowballStemmer

In [33]:
#help(SnowballStemmer)
snowball_obj = SnowballStemmer('english')

for var in Given_list:
    print(var+"--->"+snowball_obj.stem(var))

words--->word
eats--->eat
eatern--->eatern
writing--->write
writes--->write
programming--->program
program--->program
history--->histori
finally--->final
finalized--->final


In [34]:
# Porterstemmer Vs Snowballstemmer

stemming_obj.stem('fairly'),snowball_obj.stem('fairly')

('fairli', 'fair')

In [35]:
#Lemmatization
#---------------->lemma

from nltk.stem import WordNetLemmatizer
lemmatizer_obj = WordNetLemmatizer()
lemmatizer_obj.lemmatize('history')

LookupError: 
**********************************************************************
  Resource wordnet not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('wordnet')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load corpora/wordnet

  Searched in:
    - 'C:\\Users\\karth/nltk_data'
    - 'C:\\ProgramData\\anaconda3\\nltk_data'
    - 'C:\\ProgramData\\anaconda3\\share\\nltk_data'
    - 'C:\\ProgramData\\anaconda3\\lib\\nltk_data'
    - 'C:\\Users\\karth\\AppData\\Roaming\\nltk_data'
    - 'C:\\nltk_data'
    - 'D:\\nltk_data'
    - 'E:\\nltk_data'
**********************************************************************


In [36]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\karth\AppData\Roaming\nltk_data...


True

In [37]:
from nltk.stem import WordNetLemmatizer
lemmatizer_obj = WordNetLemmatizer()
lemmatizer_obj.lemmatize('history')

'history'

In [38]:
lemmatizer_obj.lemmatize('eating')

'eating'

In [39]:
lemmatizer_obj.lemmatize('going')

'going'

In [40]:
lemmatizer_obj.lemmatize('going',pos='v')

'go'

In [42]:
for var in Given_list:
    print(var+'----->'+lemmatizer_obj.lemmatize(var,pos='v'))

words----->word
eats----->eat
eatern----->eatern
writing----->write
writes----->write
programming----->program
program----->program
history----->history
finally----->finally
finalized----->finalize


In [43]:
from nltk.corpus import stopwords

nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\karth\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.


True

In [44]:
stopwords.words('english')

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'on

In [45]:
stopwords.words('french')

['au',
 'aux',
 'avec',
 'ce',
 'ces',
 'dans',
 'de',
 'des',
 'du',
 'elle',
 'en',
 'et',
 'eux',
 'il',
 'ils',
 'je',
 'la',
 'le',
 'les',
 'leur',
 'lui',
 'ma',
 'mais',
 'me',
 'même',
 'mes',
 'moi',
 'mon',
 'ne',
 'nos',
 'notre',
 'nous',
 'on',
 'ou',
 'par',
 'pas',
 'pour',
 'qu',
 'que',
 'qui',
 'sa',
 'se',
 'ses',
 'son',
 'sur',
 'ta',
 'te',
 'tes',
 'toi',
 'ton',
 'tu',
 'un',
 'une',
 'vos',
 'votre',
 'vous',
 'c',
 'd',
 'j',
 'l',
 'à',
 'm',
 'n',
 's',
 't',
 'y',
 'été',
 'étée',
 'étées',
 'étés',
 'étant',
 'étante',
 'étants',
 'étantes',
 'suis',
 'es',
 'est',
 'sommes',
 'êtes',
 'sont',
 'serai',
 'seras',
 'sera',
 'serons',
 'serez',
 'seront',
 'serais',
 'serait',
 'serions',
 'seriez',
 'seraient',
 'étais',
 'était',
 'étions',
 'étiez',
 'étaient',
 'fus',
 'fut',
 'fûmes',
 'fûtes',
 'furent',
 'sois',
 'soit',
 'soyons',
 'soyez',
 'soient',
 'fusse',
 'fusses',
 'fût',
 'fussions',
 'fussiez',
 'fussent',
 'ayant',
 'ayante',
 'ayantes',


In [49]:
#help(stopwords)

In [50]:
from nltk.tokenize import word_tokenize
msg = '''This is an example displaying off list of or collection stop word filters'''

words =word_tokenize(msg)
words

['This',
 'is',
 'an',
 'example',
 'displaying',
 'off',
 'list',
 'of',
 'or',
 'collection',
 'stop',
 'word',
 'filters']

In [55]:
# convert to lowercase chars
L=[]
for var in words:
    r = var.lower()
    L.append(r)

L



['this',
 'is',
 'an',
 'example',
 'displaying',
 'off',
 'list',
 'of',
 'or',
 'collection',
 'stop',
 'word',
 'filters']

In [58]:
filtered_words = [var for var in words if var.lower() not in stopwords.words('english')]
filtered_words

['example', 'displaying', 'list', 'collection', 'stop', 'word', 'filters']

In [59]:
L=[]
for var in [15,25,35,45,46,50,55]:
    if(var >45):
        L.append(var)

L

[46, 50, 55]

In [60]:
[var for var in [15,25,35,45,46,50,55] if var > 45]

[46, 50, 55]

In [61]:
# To get list stop words from other languages
stopwords.fileids()

['albanian',
 'arabic',
 'azerbaijani',
 'basque',
 'belarusian',
 'bengali',
 'catalan',
 'chinese',
 'danish',
 'dutch',
 'english',
 'finnish',
 'french',
 'german',
 'greek',
 'hebrew',
 'hinglish',
 'hungarian',
 'indonesian',
 'italian',
 'kazakh',
 'nepali',
 'norwegian',
 'portuguese',
 'romanian',
 'russian',
 'slovene',
 'spanish',
 'swedish',
 'tajik',
 'tamil',
 'turkish']

In [62]:
stopwords.words('arabic')

['إذ',
 'إذا',
 'إذما',
 'إذن',
 'أف',
 'أقل',
 'أكثر',
 'ألا',
 'إلا',
 'التي',
 'الذي',
 'الذين',
 'اللاتي',
 'اللائي',
 'اللتان',
 'اللتيا',
 'اللتين',
 'اللذان',
 'اللذين',
 'اللواتي',
 'إلى',
 'إليك',
 'إليكم',
 'إليكما',
 'إليكن',
 'أم',
 'أما',
 'أما',
 'إما',
 'أن',
 'إن',
 'إنا',
 'أنا',
 'أنت',
 'أنتم',
 'أنتما',
 'أنتن',
 'إنما',
 'إنه',
 'أنى',
 'أنى',
 'آه',
 'آها',
 'أو',
 'أولاء',
 'أولئك',
 'أوه',
 'آي',
 'أي',
 'أيها',
 'إي',
 'أين',
 'أين',
 'أينما',
 'إيه',
 'بخ',
 'بس',
 'بعد',
 'بعض',
 'بك',
 'بكم',
 'بكم',
 'بكما',
 'بكن',
 'بل',
 'بلى',
 'بما',
 'بماذا',
 'بمن',
 'بنا',
 'به',
 'بها',
 'بهم',
 'بهما',
 'بهن',
 'بي',
 'بين',
 'بيد',
 'تلك',
 'تلكم',
 'تلكما',
 'ته',
 'تي',
 'تين',
 'تينك',
 'ثم',
 'ثمة',
 'حاشا',
 'حبذا',
 'حتى',
 'حيث',
 'حيثما',
 'حين',
 'خلا',
 'دون',
 'ذا',
 'ذات',
 'ذاك',
 'ذان',
 'ذانك',
 'ذلك',
 'ذلكم',
 'ذلكما',
 'ذلكن',
 'ذه',
 'ذو',
 'ذوا',
 'ذواتا',
 'ذواتي',
 'ذي',
 'ذين',
 'ذينك',
 'ريث',
 'سوف',
 'سوى',
 'شتان',
 'عدا',
 'عسى',
 'عل'

In [63]:
import stopwordsiso

ModuleNotFoundError: No module named 'stopwordsiso'

In [64]:
pip install stopwordsiso

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [66]:
import stopwordsiso as stopwords
stopwords.stopwords('hi')

{'अंदर',
 'अत',
 'अदि',
 'अप',
 'अपना',
 'अपनि',
 'अपनी',
 'अपने',
 'अभि',
 'अभी',
 'आदि',
 'आप',
 'इंहिं',
 'इंहें',
 'इंहों',
 'इतयादि',
 'इत्यादि',
 'इन',
 'इनका',
 'इन्हीं',
 'इन्हें',
 'इन्हों',
 'इस',
 'इसका',
 'इसकि',
 'इसकी',
 'इसके',
 'इसमें',
 'इसि',
 'इसी',
 'इसे',
 'उंहिं',
 'उंहें',
 'उंहों',
 'उन',
 'उनका',
 'उनकि',
 'उनकी',
 'उनके',
 'उनको',
 'उन्हीं',
 'उन्हें',
 'उन्हों',
 'उस',
 'उसके',
 'उसि',
 'उसी',
 'उसे',
 'एक',
 'एवं',
 'एस',
 'एसे',
 'ऐसे',
 'ओर',
 'और',
 'कइ',
 'कई',
 'कर',
 'करता',
 'करते',
 'करना',
 'करने',
 'करें',
 'कहते',
 'कहा',
 'का',
 'काफि',
 'काफ़ी',
 'कि',
 'किंहें',
 'किंहों',
 'कितना',
 'किन्हें',
 'किन्हों',
 'किया',
 'किर',
 'किस',
 'किसि',
 'किसी',
 'किसे',
 'की',
 'कुछ',
 'कुल',
 'के',
 'को',
 'कोइ',
 'कोई',
 'कोन',
 'कोनसा',
 'कौन',
 'कौनसा',
 'गया',
 'घर',
 'जब',
 'जहाँ',
 'जहां',
 'जा',
 'जिंहें',
 'जिंहों',
 'जितना',
 'जिधर',
 'जिन',
 'जिन्हें',
 'जिन्हों',
 'जिस',
 'जिसे',
 'जीधर',
 'जेसा',
 'जेसे',
 'जैसा',
 'जैसे',
 'जो',
 'तक',
 'तब',
 

In [ ]:
## Task
##------
Take a pargraph (or) Get some short story 
|
Apply Portstemmer 
Apply stopwords
|
word tokenize 
|
display input paragraph into sentence 

####
Apply stopwords 
Get unique words - set() #  set(['data1','data2','data1']) ->{'data1','data2'}
|
apply stemming
####

Apply - WordNetLemmatizer 
|       
| - pos='v'
convert all the list of words into sentences

In [67]:
corpus='''Vikram Sarabhai, a renowned Indian scientist and industrialist, is celebrated for his 
contributions to India's space program and his vision for utilizing science and technology 
for societal development. 
He is widely regarded as the father of the Indian space program. 
A key part of his legacy is the establishment of the Indian Space Research Organisation'''

In [71]:
from nltk.stem import PorterStemmer
from nltk.corpus import stopwords
#stopwords.words('english')
stemmer = PorterStemmer()
docs = nltk.sent_tokenize(corpus)  # paragrapgh -> sentence
print(type(docs),len(docs))

## Apply stopwords
## ----------------
for var in range(len(docs)):
    words = nltk.word_tokenize(docs[var])
    words = [stemmer.stem(word) for word in words if word not in set(stopwords.words('english'))]
    docs[var] = " ".join(words)

<class 'list'> 3


In [72]:
docs

["vikram sarabhai , renown indian scientist industrialist , celebr contribut india 's space program vision util scienc technolog societ develop .",
 'he wide regard father indian space program .',
 'a key part legaci establish indian space research organis']

In [75]:
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()

docs = nltk.sent_tokenize(corpus)

for var in range(len(docs)):
    words = nltk.word_tokenize(docs[var])
    words = [lemmatizer.lemmatize(word,pos='v') for word in words if word not in set(stopwords.words('english'))]
    docs[var] = ' '.join(words) # convert all the list of words into sentences 
    

In [76]:
docs

["Vikram Sarabhai , renowned Indian scientist industrialist , celebrate contributions India 's space program vision utilize science technology societal development .",
 'He widely regard father Indian space program .',
 'A key part legacy establishment Indian Space Research Organisation']

In [77]:
from nltk.util import ngrams
from nltk.tokenize import word_tokenize

In [83]:
data = 'likes read NLP applications'

token = word_tokenize(data)
#help(ngrams)
list(ngrams(token,1))

[('likes',), ('read',), ('NLP',), ('applications',)]

In [84]:
# bigrams
list(ngrams(token,2))

[('likes', 'read'), ('read', 'NLP'), ('NLP', 'applications')]

In [85]:
# trigram
list(ngrams(token,3))

[('likes', 'read', 'NLP'), ('read', 'NLP', 'applications')]

In [88]:
# 4gram
list(ngrams(token,4))

[('likes', 'read', 'NLP', 'applications')]

In [89]:
# 5gram
list(ngrams(token,5))

[]

In [93]:
len(docs[0])

163

In [96]:
L = list(ngrams(docs[0],n=2))
len(L)

162

In [100]:
L=['data','test']
    ----
#for var in ''.join(L):
#  print(var)


In [106]:
len(docs[1])

46

In [109]:
print(type(docs[1]))

<class 'str'>


In [110]:
docs[1]

'He widely regard father Indian space program .'

In [112]:
token = word_tokenize(docs[1])
list(ngrams(token,2))

[('He', 'widely'),
 ('widely', 'regard'),
 ('regard', 'father'),
 ('father', 'Indian'),
 ('Indian', 'space'),
 ('space', 'program'),
 ('program', '.')]

In [126]:
## One-Hot encoding
##------------------
# string -> number 
# numpy.array(data).reshape(-1,1) =>2D
import numpy as np
from sklearn.preprocessing import OneHotEncoder

data = ['He','widely','regard','father','Indian','space','program']

data = np.array(data).reshape(-1,1) # 2D

encoder = OneHotEncoder(sparse_output=False)
one_hot = encoder.fit_transform(data)
print(encoder.categories_)
print('')
print('one-Hot encoded value:',one_hot)

[array(['He', 'Indian', 'father', 'program', 'regard', 'space', 'widely'],
      dtype='<U7')]

one-Hot encoded value: [[1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0. 0.]]


In [ ]:
############ END OF THE DAY1 ####################